# Generated by Django 5.1.4 on 2024-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_service_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Appointment Date'),
        ),
    ]
